name: Deploy vendor.businesssafeit.com

on:
  push:
    branches:
      - main # আপনার যে ব্র্যাঞ্চে পুশ করলে লাইভ হবে (main/master)

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: SSH and Deploy to VPS
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          cd /home/businesssafeit-vendor/htdocs/vendor.businesssafeit.com
          git pull origin main