name: Deploy vendor.businesssafeit.com

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: SSH and Deploy to VPS
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          cd /home/businesssafeit-vendor/htdocs/vendor.businesssafeit.com
          
          # Clean local untracked/cache changes to avoid pull conflicts
          git reset --hard HEAD
          git clean -fd
          git pull origin main

          # Install packages and run migrations
          composer install --no-interaction --prefer-dist --optimize-autoloader
          php artisan migrate --force

          # Generate Swagger Docs automatically on deploy
          php artisan l5-swagger:generate

          # Clear & Cache Configurations
          php artisan config:clear
          php artisan route:clear
          php artisan view:clear
          php artisan optimize